bridge:
  domain: "matrix.proglangdesign.net"
  homeserverUrl: "http://localhost:8008"
  enableSelfServiceBridging: false
  disableEveryoneMention: true
  disableHereMention: true

auth:
  clientID: "541288099972513792"
  botToken: "\discordBotToken"

database:
#  userStorePath: "\data/matrix-appservice-discord/user-store.db"
#  roomStorePath: "\data/matrix-appservice-discord/room-store.db"
  filename: "\data/matrix-appservice-discord/discord.db"

room:
  defaultVisibility: "public"

channel:
  namePattern: ":name | :guild"
